### ISSUE TITLE
Ranging Beacons

### ISSUE THREAD

**Issue by JamesSwag** [alann-maulana/flutter_beacon#37]
Hello, 

I'm new to flutter and I want to create a Beacon Scanning app, if I simply want to scan any nearby beacons and get their UUID do I use the ranging method?

**Comment by alann-maulana** [comment]
Hi @JamesSwag 

yes, you can use the ranging method to find nearby beacons. In Android you can find all beacons without UUD, but in iOS you must define at least a region with identifier and UUID as [example here](https://github.com/alann-maulana/flutter_beacon#ranging-beacons).

**Comment by JamesSwag** [comment]
Thank You, however if I need to set an identifier and UUID for iOS wouldn't that be the same as just monitoring.

**Comment by alann-maulana** [comment]
Yep, both ranging and monitoring beacons are using region as well..

**Comment by JamesSwag** [comment]
Is there anyway I can monitor for multiple different regions each with a different UUID?

**Comment by alann-maulana** [comment]
Of course you can @JamesSwag but FYI, the more region you put to ranging or monitoring beacons will slow down your phone. Especially on lower end and old phone.

**Comment by luisestudioalfa** [comment]
So, if i have 500 beacons, do i have to create a Region with 500 elements ( each with its uuid and identifier)? there is no way to group them, so the región only has one or some items? 

For example monitoring all the beacons with uuid has 33333333-2222-1111-4444-XXXXXXXXXXXXX? 

Where the XXX represents the identifier of the beacons, so that you don't have to define 500 regions?

**Comment by alann-maulana** [comment]
That's a huge amount of beacon btw @luisestudioalfa. One of my project, use almost a hundred of beacons. So instead of creating every region ranging for every beacons, I only scan the UUID only. When beacon(s) with current UUID, I will immediately filtered it using the existing major and minor of these beacons.

There are a powerfull search engine and a tons of article if you are curious about ranging vs monitoring beacons, [click this link](https://www.google.com/search?q=ranging+and+monitoring+beacons).
