### ISSUE TITLE
Sample app given in repo cannot detect iBeacon next to Android phone.

### ISSUE THREAD

**Issue by Ollie-spoon** [alann-maulana/flutter_beacon#73]
I've been trying to use your library to detect beacons nearby in an app and have bought an "Avvel" iBeacon that I have set up and can detect using the "BLE Scanner" app from the google play store. I made sure to allow location tracking, as well as having a constant wifi connection and having my Bluetooth on. It just doesn't pick it up and by that, I mean that I have a spinning circle in the middle of the screen and in my console in "Android Studio" I get the message

_"I/flutter (15631): {"region":{"identifier":"Cubeacon","proximityUUID":"cb10023f-a318-3394-4199-a8730c7c1aec"},"beacons":[]}"_

every second or so.

The phone is an original Pixel but as I said, I can detect the beacon using another beacon detection app so I doubt its a hardware issue.

Below is the image of the screen. (Taken from the android emulator in android studio for ease of screenshotting rather than the actual phone).
![image](https://user-images.githubusercontent.com/68749892/94687238-e8d5da80-0323-11eb-806c-4ef3a236d730.png)

Any suggestions or solutions would be greatly appreciated. If you need anything else from me then I would be more than happy to oblige.

**Edit:** For clarification the app that I used was from the master branch here - https://github.com/alann-maulana/flutter_beacon.

**Comment by EricHier** [comment]
I've exactly got the same problem. Did you solve it?

**Comment by j04ntoh** [comment]
i'm not detecting any beacons on android. It's working fine on iOS.

**Comment by j04ntoh** [comment]
<img width="1680" alt="Screenshot 2020-10-30 at 4 30 37 PM" src="https://user-images.githubusercontent.com/284813/97677603-76e0e480-1acd-11eb-9b67-cac971b2b8d0.png">
i have 2 copies of flutters. 1 working, the other is not. can it be compileSdkVersion?

**Comment by uzuraegg** [comment]
I was facing the same problem but solved it. If you are using the sample app as is, you need to change the regions in the sample code properly.

**Comment by TamojitSaha** [comment]
@uzuraegg I am having the same issue as above. Can you please share your modification with detail?
I am a beginner in the Flutter world.

**Comment by jacobmealey** [comment]
Hello, I am also experiencing this issue, though I am not sure what to change the ranging to, I have tried changing the range to blank screens in hope that it just detect all beacons or something. when using the android-beacon-library by altbeacon I also had to add :
```java
  beaconManager.getBeaconParsers().add(new BeaconParser().
                        setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));
```
in order to get the beacon to be detected, is there something similar for this library I should try? 

P.S. @uzuraegg what did you change the region to?

**Comment by MtPython** [comment]
It could be the [issue](https://github.com/alann-maulana/flutter_beacon/issues/67#issuecomment-719425702) with the *...SdkVersion* 29+, currently the master branch seems to work with version 28 only.

You could also add support for you exact type of beacon as mentioned [here](https://github.com/alann-maulana/flutter_beacon/issues/55#issuecomment-643713214) as a reply to @jacobmealey 

I'd also recommend removing the `proximityUUID` property in `Region` declaration, if you're testing for Android, because only the `identifier` is required.

**Comment by PeterPoll** [comment]
Hello, I have the same problem but I didn't find any solution. Can anyone send me here code which works to check it ? Thank you very much! My email is pollakis.p6@gmail.com

**Comment by j04ntoh** [comment]
@PeterPoll It was mentioned in one of the threads that pub.dev plugin is old. You needa use the github version and upgrade your sdkversion to 30.

**Comment by PeterPoll** [comment]
What you mean exactly "use the GitHub version" ? Can you provide me an example? Sorry but new on all of this.

**Comment by j04ntoh** [comment]
@PeterPoll 

pubspec.yaml
  flutter_beacon: 
    git: https://github.com/alann-maulana/flutter_beacon.git

**Comment by PeterPoll** [comment]
@j04ntoh  Ok I will check it, thank you very much!

**Comment by PeterPoll** [comment]
This works for android and IOS ?

I'm trying to detect my beacon but doesn't work

Thank you!

**Comment by PeterPoll** [comment]
Also I tried the above change on pubspec.yaml and I'm getting error.

[image: εικόνα.png]

**Comment by alann-maulana** [comment]
Please update to [flutter_beacon: 0.4.0](https://pub.dev/packages/flutter_beacon/versions/0.4.0) to fix regarding this issue.
